-- using mariadb
CREATE TABLE APPLICANTS (
    APPLICANT_ID INT AUTO_INCREMENT,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    DOB DATE NOT NULL, -- Date of birth
    ADDRESS VARCHAR(50) NOT NULL,
    ZIP_CODE VARCHAR(10) NOT NULL,
    CITY VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    CONSTRAINT applicants_pk PRIMARY KEY (APPLICANT_ID)
);

ALTER TABLE APPLICANTS
ADD APPROVED BOOLEAN;